//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationsDolphinDiscoveryII.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class reservacionesEntities : DbContext
    {
        public reservacionesEntities()
            : base("name=reservacionesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cities> Cities { get; set; }
        public DbSet<Hotels> Hotels { get; set; }
        public DbSet<HotelsInCities> HotelsInCities { get; set; }
        public DbSet<PricePerHabitationInCity> PricePerHabitationInCity { get; set; }
        public DbSet<Rooms> Rooms { get; set; }
        public DbSet<StagesAndAges> StagesAndAges { get; set; }
    }
}
