//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationsDolphinDiscoveryII.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rooms
    {
        public Rooms()
        {
            this.PricePerHabitationInCity = new HashSet<PricePerHabitationInCity>();
        }
    
        public int pkRoom { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<PricePerHabitationInCity> PricePerHabitationInCity { get; set; }
    }
}
